# Generated by Django 3.2 on 2022-11-06 15:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaleChance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chanceSource', models.CharField(db_column='chance_source', help_text='信息来源', max_length=300)),
                ('customerId', models.IntegerField(db_column='customer_id', help_text='客户id')),
                ('customerName', models.CharField(db_column='customer_name', help_text='客户名称', max_length=100)),
                ('cgjl', models.IntegerField(db_column='cgjl', help_text='成功机率', null=True)),
                ('overview', models.CharField(db_column='overview', help_text='概要', max_length=300, null=True)),
                ('linkMan', models.CharField(db_column='link_man', help_text='联系人', max_length=20)),
                ('linkPhone', models.CharField(db_column='link_phone', help_text='联系电话', max_length=20)),
                ('description', models.CharField(db_column='description', help_text='描述', max_length=1000)),
                ('createMan', models.CharField(db_column='create_man', help_text='创建人', max_length=20)),
                ('assignMan', models.CharField(db_column='assign_man', help_text='分配给谁', max_length=20, null=True)),
                ('assignTime', models.DateTimeField(db_column='assign_time', help_text='分配时间', null=True)),
                ('state', models.CharField(db_column='state', help_text='状态', max_length=20, null=True)),
                ('devResult', models.CharField(db_column='dev_result', help_text='开发状态', max_length=20, null=True)),
                ('isValid', models.IntegerField(db_column='is_valid', default=1, null=True)),
                ('createDate', models.DateTimeField(auto_now_add=True, db_column='create_date', help_text='创建时间', null=True)),
                ('updateDate', models.DateTimeField(db_column='update_date', help_text='更新时间', max_length=20, null=True)),
                ('deleted', models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0, help_text='是否删除')),
            ],
            options={
                'db_table': 't_sale_chance',
            },
        ),
        migrations.CreateModel(
            name='CusDevPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planItem', models.CharField(db_column='plan_item', help_text='执行内容', max_length=300)),
                ('planDate', models.DateTimeField(auto_now_add=True, db_column='plan_date', help_text='执行时间', max_length=20)),
                ('exeAffect', models.CharField(db_column='exe_affect', help_text='执行效果', max_length=100)),
                ('isValid', models.IntegerField(db_column='is_valid')),
                ('createDate', models.DateTimeField(auto_now_add=True, db_column='create_date', help_text='创建时间', null=True)),
                ('updateDate', models.DateTimeField(db_column='update_date', default=datetime.datetime.now, help_text='更新时间', max_length=20, null=True)),
                ('saleChance', models.ForeignKey(db_column='sale_chance_id', db_constraint=False, help_text='关联营销机会', on_delete=django.db.models.deletion.DO_NOTHING, to='sales.salechance')),
            ],
            options={
                'db_table': 't_cus_dev_plan',
            },
        ),
    ]
