# Generated by Django 3.2 on 2022-11-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cusdevplan',
            name='deleted',
            field=models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0, help_text='是否删除'),
        ),
    ]
