# Generated by Django 3.2 on 2022-10-30 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='CityCourse',
        ),
    ]
