# Generated by Django 3.2 on 2022-11-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerloss',
            name='deleted',
            field=models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0, null=0, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='customerreprieve',
            name='deleted',
            field=models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0, null=0, verbose_name='是否删除'),
        ),
    ]
