# Generated by Django 3.2 on 2022-10-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_city_citycourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=128, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='annual_turnover',
            field=models.CharField(max_length=128, verbose_name='年营业额'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='area',
            field=models.CharField(max_length=128, verbose_name='所在地区'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bank',
            field=models.CharField(max_length=128, verbose_name='开户银行'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bank_number',
            field=models.CharField(max_length=128, verbose_name='开户账号'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='company_num',
            field=models.CharField(max_length=128, verbose_name='营业注册号'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cusManager',
            field=models.CharField(db_column='cus_manager', max_length=128),
        ),
        migrations.AlterField(
            model_name='customer',
            name='fax',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='customer',
            name='land_tax',
            field=models.CharField(max_length=128, verbose_name='地税'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='leader_of_company',
            field=models.CharField(max_length=128, verbose_name='法人'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='level',
            field=models.CharField(max_length=128, verbose_name='客户级别'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='myd',
            field=models.CharField(max_length=128, verbose_name='客户满意度'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=128, verbose_name='客户名称'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postCode',
            field=models.CharField(db_column='post_code', max_length=128),
        ),
        migrations.AlterField(
            model_name='customer',
            name='registered_capital',
            field=models.CharField(max_length=128, verbose_name='注册资本'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='the_irs',
            field=models.CharField(max_length=128, verbose_name='国税'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='web_url',
            field=models.CharField(db_column='web_url', max_length=128),
        ),
        migrations.AlterField(
            model_name='customer',
            name='xyd',
            field=models.CharField(max_length=128, verbose_name='信用度'),
        ),
    ]
