# Generated by Django 3.2 on 2022-10-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20221030_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='deleted',
            field=models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0, null=True, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='customerloss',
            name='deleted',
            field=models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0, null=True, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='customerorders',
            name='deleted',
            field=models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0, null=True, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='customerreprieve',
            name='deleted',
            field=models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0, null=True, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='linkman',
            name='deleted',
            field=models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0, null=True, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='ordersdetail',
            name='deleted',
            field=models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0, null=True, verbose_name='是否删除'),
        ),
    ]
