# Generated by Django 3.2 on 2022-11-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20221105_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerloss',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True, db_column='create_date', null=True),
        ),
        migrations.AlterField(
            model_name='customerloss',
            name='updateDate',
            field=models.DateTimeField(auto_now_add=True, db_column='update_date', null=True),
        ),
    ]
