# Generated by Django 3.2 on 2022-10-31 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20221030_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorders',
            name='orderNo',
            field=models.CharField(db_column='order_no', max_length=64),
        ),
    ]
