# Generated by Django 3.2 on 2022-11-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20221105_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreprieve',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True, db_column='create_date', null=True),
        ),
        migrations.AlterField(
            model_name='customerreprieve',
            name='deleted',
            field=models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0, null=True, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='customerreprieve',
            name='isValid',
            field=models.IntegerField(db_column='is_valid', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='customerreprieve',
            name='updateDate',
            field=models.DateTimeField(auto_now_add=True, db_column='update_date', null=True),
        ),
    ]
