# Generated by Django 3.2 on 2022-11-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20221105_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkman',
            name='sex',
            field=models.IntegerField(max_length=4),
        ),
    ]
