# Generated by Django 3.2 on 2022-11-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20221112_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkman',
            name='sex',
            field=models.IntegerField(null=True),
        ),
    ]
