# Generated by Django 3.2 on 2022-10-20 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('birthday', models.DateTimeField(max_length=32, verbose_name='生日')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('image', models.ImageField(default='image/default.png', upload_to='image/%Y/%m')),
                ('address', models.CharField(max_length=64, verbose_name='地址')),
                ('gender', models.CharField(choices=[('man', '男'), ('woman', '女人')], default='man', max_length=12, verbose_name='性别')),
                ('username', models.CharField(max_length=24, verbose_name='用户名')),
                ('password', models.CharField(max_length=24, verbose_name='密码')),
                ('salt', models.CharField(max_length=2, verbose_name='加密盐')),
                ('true_name', models.CharField(max_length=20, null=True)),
                ('state', models.IntegerField(choices=[('0', '未审核'), ('1', '已审核'), ('-1', '黑名单')], default=0, verbose_name='是否审核')),
                ('isValid', models.IntegerField(db_column='is_valid', default=0)),
                ('create_time', models.DateTimeField(db_column='create_time', default=datetime.datetime(2022, 10, 20, 20, 36, 18, 120267))),
                ('update_time', models.DateTimeField(db_column='update_time', default=datetime.datetime(2022, 10, 20, 20, 36, 18, 120267))),
                ('company', models.CharField(max_length=24, verbose_name='所属公司')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'T2_user',
            },
        ),
    ]
