# Generated by Django 3.2 on 2022-11-23 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduleName', models.CharField(db_column='module_name', help_text='权限名称', max_length=64)),
                ('moduleStyle', models.CharField(db_column='module_style', help_text='样式', max_length=128, null=True)),
                ('url', models.CharField(db_column='url', max_length=120, null=True)),
                ('parentOptValue', models.CharField(db_column='parent_opt_value', help_text='父级操作值', max_length=64, null=True)),
                ('grade', models.IntegerField(db_column='grade')),
                ('optValue', models.CharField(db_column='opt_value', max_length=20)),
                ('orders', models.IntegerField(db_column='orders', help_text='排序')),
                ('isValid', models.IntegerField(db_column='is_valid', default=1, help_text='是否可用')),
                ('createDate', models.DateTimeField(auto_now_add=True, db_column='create_date', null=True)),
                ('updateDate', models.DateTimeField(auto_now_add=True, db_column='update_date', max_length=64, null=True)),
                ('parent', models.ForeignKey(db_column='parent_id', db_constraint=False, default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='system.module')),
            ],
            options={
                'db_table': 't2_module',
            },
        ),
    ]
