# Generated by Django 3.2 on 2022-10-22 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='城市名称')),
                ('add_time', models.DateField(verbose_name=datetime.datetime.now)),
                ('des', models.CharField(max_length=200, verbose_name='u描述')),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=64, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(max_length=32, null=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(max_length=24, null=True, verbose_name='所属公司'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(db_column='create_time', default=datetime.datetime(2022, 10, 22, 13, 44, 42, 829514)),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('man', '男'), ('woman', '女人')], default='man', max_length=12, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='image/default.png', null=True, upload_to='image/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_time',
            field=models.DateTimeField(db_column='update_time', default=datetime.datetime(2022, 10, 22, 13, 44, 42, 829514)),
        ),
    ]
