# Generated by Django 3.2 on 2022-10-22 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20221022_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(db_column='create_time', default=datetime.datetime(2022, 10, 22, 13, 54, 30, 398383)),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_time',
            field=models.DateTimeField(db_column='update_time', default=datetime.datetime(2022, 10, 22, 13, 54, 30, 399381)),
        ),
    ]
