# Generated by Django 3.2 on 2022-11-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='orders',
            field=models.IntegerField(db_column='orders', help_text='排序', null=True),
        ),
    ]
