# Generated by Django 3.2 on 2022-11-26 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_alter_module_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoleName', models.CharField(db_column='role_name', help_text='角色名称', max_length=24)),
                ('RoleRemark', models.CharField(db_column='role_remark', help_text='角色名称', max_length=64)),
                ('CreateDate', models.DateTimeField(auto_now_add=True, db_column='create_date', help_text='创建时间', null=True)),
                ('UpdateDate', models.DateTimeField(auto_now_add=True, db_column='update_date', null=True)),
                ('isValid', models.IntegerField(db_column='is_valid', default=1, help_text='是否可用')),
            ],
            options={
                'db_table': 't2_role',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AclValue', models.CharField(max_length=64, null=True)),
                ('CreateDate', models.DateTimeField(auto_now_add=True, db_column='create_date', help_text='创建时间', null=True)),
                ('UpdateDate', models.DateTimeField(auto_now_add=True, db_column='update_date', null=True)),
                ('isValid', models.IntegerField(db_column='is_valid', default=1, help_text='是否可用')),
                ('ModuleId', models.ForeignKey(db_column='module_id', on_delete=django.db.models.deletion.DO_NOTHING, to='system.module')),
                ('RoleId', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.DO_NOTHING, to='system.role')),
            ],
            options={
                'db_table': 't2_role_permission',
            },
        ),
    ]
