# Generated by Django 3.2 on 2022-10-22 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20221022_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'T2_city', 'verbose_name_plural': 'T2_city'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='user',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='true_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='update_time',
        ),
        migrations.AddField(
            model_name='user',
            name='createDate',
            field=models.DateTimeField(db_column='create_date', default=datetime.datetime(2022, 10, 22, 14, 7, 59, 253315), verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=30, null=True, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='电话号码'),
        ),
        migrations.AddField(
            model_name='user',
            name='truename',
            field=models.CharField(max_length=20, null=True, verbose_name='昵称'),
        ),
        migrations.AddField(
            model_name='user',
            name='updateDate',
            field=models.DateTimeField(db_column='update_date', null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='isValid',
            field=models.IntegerField(db_column='is_valid', default=1, verbose_name='是否可用'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(max_length=4, verbose_name='盐加密'),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.IntegerField(default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, verbose_name='用户名'),
        ),
    ]
