# Generated by Django 3.2 on 2022-11-28 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_role_rolepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreateDate', models.DateTimeField(auto_now_add=True, db_column='create_date', help_text='创建时间', null=True)),
                ('UpdateDate', models.DateTimeField(auto_now_add=True, db_column='update_date', null=True)),
                ('isValid', models.IntegerField(db_column='is_valid', default=1, help_text='是否可用')),
                ('RoleId', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.DO_NOTHING, to='system.role')),
                ('UserId', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to='system.user')),
            ],
            options={
                'db_table': 't2_user_role',
            },
        ),
    ]
