# Generated by Django 3.2 on 2022-11-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted',
            field=models.IntegerField(default=0, null=True, verbose_name='是否删除'),
        ),
    ]
